# -----------------------
# Netlify Build Settings
# -----------------------
[build]
 # base    = "client"                       # your React frontend folder
  publish = "dist"                         # Vite outputs production files here
  command = "npm install && npm run build" # install deps and build

# -----------------------
# SPA Fallback for React Router
# -----------------------
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = { "!file" = true }  # only redirect if the file does not exist

# -----------------------
# API Proxy (if you have a backend)
# -----------------------
[[redirects]]
  from = "/api/*"
  to = "https://sanyug-server.onrender.com/:splat"
  status = 200
  force = true

# -----------------------
# Security Headers + CSP
# -----------------------
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    # Allow Google Sign-In scripts and styles
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://accounts.google.com https://apis.google.com;
      style-src 'self' 'unsafe-inline' 'https://accounts.google.com/gsi/style' ;
      frame-src 'self' https://accounts.google.com" ;
      img-src 'self' data: https://lh3.googleusercontent.com;
      connect-src 'self' https://sanyug-server.onrender.com https://accounts.google.com https://apis.google.com ;
      font-src 'self';
    """
